// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ActionBar: typeof import('./src/components/ActionBar/index.vue')['default']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    Board: typeof import('./src/components/Board/index.vue')['default']
    ChatBox: typeof import('./src/components/ChatBox/index.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    ImgPreviewModal: typeof import('./src/components/ImgPreviewModal/index.vue')['default']
    MessageItem: typeof import('./src/components/MessageItem/index.vue')['default']
    MessageList: typeof import('./src/components/MessageList/index.vue')['default']
    MessageTime: typeof import('./src/components/MessageTime/index.vue')['default']
    QuestionAddModal: typeof import('./src/components/QuestionAddModal/index.vue')['default']
    QuestionsSortModal: typeof import('./src/components/QuestionsSortModal/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenesBar: typeof import('./src/components/ScenesBar/index.vue')['default']
    ScenesModal: typeof import('./src/components/ScenesModal/index.vue')['default']
    SessionList: typeof import('./src/components/SessionList/index.vue')['default']
    SettingsModal: typeof import('./src/components/SettingsModal/index.vue')['default']
    ShortcutsModal: typeof import('./src/components/ShortcutsModal/index.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar/index.vue')['default']
    SideTopbar: typeof import('./src/components/SideTopbar/index.vue')['default']
    WebdavModal: typeof import('./src/components/WebdavModal/index.vue')['default']
  }
}
